defaults:
  - base

_target_: gflownet.envs.molecular.MolecelarSeq

id: molecular
func: nupack energy
# Minimum and maximum length for the sequences
min_seq_length: 3
max_seq_length: 10
# Number of letters in alphabet

# Minimum and maximum number of steps in the action space
min_word_len: 1
max_word_len: 1

# vocab_path: /home/lishuwang/project/GFlowNet/gflownet-molbart/vocab.txt

